# Generated by Django 3.1.4 on 2020-12-19 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20201219_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('C', 'Cart'), ('P', 'Pending'), ('OFD', 'Out for delivery'), ('D', 'Delivered')], default='P', max_length=200),
        ),
    ]
